version: "3.9"
services:
  app:
    image: ghcr.io/pefribeiro/ros2-tb3:main
    platform: linux/amd64
    command: ["tail", "-f", "/dev/null"]
    environment:
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - DISPLAY=:0
      - PULSE_SEVER=/mnt/wslg/PulseServer
    volumes:
      - type: bind
        source: /usr/lib/wsl
        target: /usr/lib/wsl
        read_only: true
      - type: bind
        source: /run/desktop/mnt/host/wslg
        target: /mnt/wslg
        read_only: true
      - type: bind
        source: /run/desktop/mnt/host/wslg/.X11-unix
        target: /tmp/.X11-unix
        read_only: true